"""add verification reset otp columns

Revision ID: 1cd16c8d6ca7
Revises: 5e367a8d7484
Create Date: 2026-06-07 12:44:02.693838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd16c8d6ca7'
down_revision: Union[str, Sequence[str], None] = '5e367a8d7484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_otp_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_otp_expires')
    op.drop_column('users', 'reset_otp')
    op.drop_column('users', 'verification_token')
    # ### end Alembic commands ###
