"""add journal_entries table

Revision ID: 2b1e7b910d98
Revises: df53edb85182
Create Date: 2026-07-29 12:48:45.672194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b1e7b910d98'
down_revision: Union[str, Sequence[str], None] = 'df53edb85182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('water_intake_liters', sa.Float(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('exercise_minutes', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_journal_user_date')
    )
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.drop_column('scans', 'photo_url_1')
    op.drop_column('scans', 'photo_angle_2')
    op.drop_column('scans', 'photo_url_2')
    op.drop_column('scans', 'photo_url_3')
    op.drop_column('scans', 'photo_confidence_1')
    op.drop_column('scans', 'individual_photo_scores')
    op.drop_column('scans', 'photo_confidence_3')
    op.drop_column('scans', 'photo_angle_1')
    op.drop_column('scans', 'photo_confidence_2')
    op.drop_column('scans', 'photo_angle_3')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('photo_angle_3', sa.VARCHAR(), server_default=sa.text("'right'::character varying"), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('photo_confidence_2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('photo_angle_1', sa.VARCHAR(), server_default=sa.text("'front'::character varying"), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('photo_confidence_3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('individual_photo_scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('photo_confidence_1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('photo_url_3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('photo_url_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('photo_angle_2', sa.VARCHAR(), server_default=sa.text("'left'::character varying"), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('photo_url_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
